# Generated by Django 5.0.3 on 2024-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveCourse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('duration_in_months', models.IntegerField(default=6)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='studentcourse.electivecourse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
