# Generated by Django 5.0.3 on 2024-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcourse', '0002_alter_electivecourse_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivecourse',
            name='course_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
